# Generated by Django 6.0.2 on 2026-02-11 14:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('full_description', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='events/')),
            ],
        ),
    ]
