# Generated by Django 6.0.2 on 2026-02-11 14:04

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='projects/directions/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectdirection')),
            ],
        ),
    ]
