# Generated by Django 6.0.2 on 2026-02-11 14:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='О нас', max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('mission', ckeditor.fields.RichTextField()),
                ('values', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
    ]
